### ISSUE TITLE
Is It available for 2.1 solidus?

### ISSUE THREAD

**Issue by sechix** [deseretbook/solidus_wishlist#5]
Can use in solidus 2.1 ?
Thanks in advanced

**Comment by dgra** [comment]
@sechix We are currently working on updating this to be compatible with solidus versions later than 2.0. That work is on branch `solidus-2.0` and it should work with solidus 2.1 but I haven't explicitly tested against 2.1 yet.

**Comment by sechix** [comment]
Hello @dgra , thanks for your answer, I can test it but installing by gem gives me an error due to specific solidus 2.0 version.

**Comment by dgra** [comment]
@sechix Are you installing with the branch defined? For example, something like `gem 'solidus_wishlist', github: 'deseretbook/solidus_wishlist', branch: 'solidus-2.0'`

**Comment by sechix** [comment]
Finally I installed it in that way, I am checking but seems work correctly

**Comment by dgra** [comment]
@sechix That is good. I just wanted to let you know that we have merged that branch into master now. So you can omit the branch parameter for the gem install now, if it is working for you.
